---
server:
  port: 9090

logging:
  file: "target/webapp.log"

security:
  user:
    name: admin
    password: fuhaiwei

management:
  security:
    enabled: false

spring:
  application:
    name: "@pom.artifactId@"
  jpa:
    hibernate:
      ddl-auto: update
  data:
    rest:
      base-path: /api
  boot:
    admin:
      url: http://localhost:9091
      username: "${security.user.name}"       #These two are needed so that the client
      password: "${security.user.password}"   #can register at the protected server api
      client:
        metadata:
          user.name: "${security.user.name}"          #These two are needed so that the server
          user.password:  "${security.user.password}" #can access the proteceted client endpoints
  profiles:
    active:
      - dev

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/mzzb_dev?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: mzzb_dev
    password: mzzb_dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

---
spring:
  profiles: pro
  datasource:
    url: jdbc:mysql://localhost:3306/mzzb_pro?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: mzzb_pro
    password: mzzb_pro
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
