spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mzzb_pro?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: mzzb_pro
    password: mzzb_pro
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  data:
    rest:
      base-path: /api
server:
  port: 9090
