---
server:
  port: 9090

spring:
  application:
    name: "@pom.artifactId@"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
  profiles:
    active:
      - dev

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/mzzb_dev?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: mzzb_dev
    password: mzzb_dev
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true

---
spring:
  profiles: pro
  datasource:
    url: jdbc:mysql://localhost:3306/mzzb_pro?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: mzzb_pro
    password: mzzb_pro
  jpa:
    show-sql: false
  boot:
    admin:
      url: http://localhost:9091
      username: "${security.user.name}"       #These two are needed so that the client
      password: "${security.user.password}"   #can register at the protected server api

logging:
  file: target/webapp.log

management:
  security:
    enabled: false
  context-path: /management
