spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mzzb_dev?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: mzzb_dev
    password: mzzb_dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    rest:
      base-path: /api
  boot:
    admin:
      url: http://localhost:8080
      username: "${security.user.name}"       #These two are needed so that the client
      password: "${security.user.password}"   #can register at the protected server api
      client:
        metadata:
          user.name: "${security.user.name}"          #These two are needed so that the server
          user.password:  "${security.user.password}" #can access the proteceted client endpoints
security:
  user:
    name: admin
    password: fuhaiwei
management:
  security:
    enabled: false
logging:
  file: "target/webapp.log"
server:
  port: 9090
